name: 'character to run'
description: 'a description'

# Were we can define the inputs that our action will accept
inputs:
  characters:
    required: true
  artifactName:
    required: true
  TwitterConsumerAPIKey:
    required: true
  TwitterConsumerAPISecretKey:
    required: true
  TwitterAccessToken:
    required: true
  TwitterAccessTokenSecret:
    required: true
  BlobStorageConnectionString:
    required: true

runs:
  using: "composite"
  steps:
    
    - name: Download artifact from build job
      uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
      with:
        name: ${{ inputs.artifactName }}
        path: ./ArtifactFolder

    - name: Setup .NET
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
      with:
        dotnet-version: 8.x

    # these are needed to be able to run playwright, as it will not work with just artifact from the build job
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v3.5.3
      with:
        path: repo

    - name: Restore
      shell: bash
      run: dotnet restore repo/AzDoExtensionNews/AzDoExtensionNews.sln --locked-mode

    - name: Build
      shell: bash
      run: dotnet build repo/AzDoExtensionNews/AzDoExtensionNews.sln -c Release
    # / end of extra stuff

    - name: App Settings Variable Substitution
      uses: rajbos-actions/variable-substitution@ae7b1f3676ae374dc70282e6b9650bc50b611222 # v1.2
      with:
        files: 'repo/AzDoExtensionNews/GitHubActionsNews/bin/Release/net8.0/appsettings.json'
      env:
        TwitterConsumerAPIKey: ${{ inputs.TwitterConsumerAPIKey }}
        TwitterConsumerAPISecretKey: ${{ inputs.TwitterConsumerAPISecretKey }}
        TwitterAccessToken: ${{ inputs.TwitterAccessToken }}
        TwitterAccessTokenSecret: ${{ inputs.TwitterAccessTokenSecret }}
        BlobStorageConnectionString: ${{ inputs.BlobStorageConnectionString }}
    
    - name: Install Playwright Browsers
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $script = Join-Path $env:GITHUB_WORKSPACE 'repo/AzDoExtensionNews/GitHubActionsNews/bin/Release/net8.0/playwright.ps1'
        if (-not (Test-Path $script)) {
          throw "Playwright script not found at $script"
        }
        & $script install chromium --with-deps

    - name: Run the GitHubActionsNews application
      shell: pwsh
      run: |
        Write-Host "::group::Run the GitHubActionsNews application"
        cd repo/AzDoExtensionNews/GitHubActionsNews/bin/Release/net8.0
        dotnet GitHubActionsNews.dll ${{ inputs.characters }}
        Write-Host "::endgroup::"

    - name: Upload any error files
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        path: Error_Page_*
